#-------------------------------
# Site Settings
title: "Tim's Portfolio"
logo: '/images/portfolio-logo.png' 
logo_dark: '/images/portfolio-logo.png'
description: Welcome to my portfolio.
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Pages'
      submenu:
      - url: '/TimBunkerPortfolio/elements/'
        title: 'Elements'


#-------------------------------
# Author Settings
author:
  author_name: Tim Bunker
  author_avatar: '/images/headshot.jpg'


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_role: Software Engineer ∙ Programmer ∙ Student
  hero_title: Hi! I’m Tim <img src="/TimBunkerPortfolio/images/headshot.jpg" alt="Tim Bunkers's Picture" loading="lazy"> <br> and I am a Software Developer.
  hero_description:
  hero_button_text: There is always something to work on.
  hero_button_link: "/TimBunkerPortfolio/contact/"


#-------------------------------
# Projects Section Settings
projects:
  enable: true
  projects_title: Selected Works
  projects_description: This page houses my work and has links to all of the projects I have worked on


#-------------------------------
# Testimonials Section Settings
testimonials:
  enable: false
  testimonials_title: What People Say?
  testimonials_description: Hear from those who have experienced the transformative power of my artistry and design. These testimonials showcase the success stories born from our collaborative partnerships.
  testimonials_info: Loved by 50+ customers
  testimonial_items:
    - name: "John Smith"
      image: "/images/client-1.jpg"
      designation: "CEO of Creative Innovations"
      content : "Collaborating was a seamless experience. The creativity and execution brought our project to life in ways we couldn't have imagined."

    - name: "David Wilson"
      image: "/images/client-2.jpg"
      designation: "Senior Designer at Elegance Studios"
      content : "The elegant and modern design aesthetic was exactly what we needed. The work was both inspiring and flawlessly executed."

    - name: "Sarah Davis"
      image: "/images/client-3.jpg"
      designation: "Director of FutureTech Labs"
      content : "The blend of technology and art was masterful. Every piece showcased a deep understanding of both disciplines."


#-------------------------------
# Blog Section Settings
blog:
  enable: false
  blog_title: From My Blog
  blog_description: Dive into a world of creativity and inspiration through my blog. Here, I share insights into my artistic process, design trends, and the stories behind my latest projects.


#-------------------------------
# About Section Settings
about:
  enable: true
  about_image: '/TimBunkerPortfolio/images/01.jpg'
  about_title: Short Story About Me
  about_description: As a computer scientist I became interested in computers by asking big questions that seemingly only computer technology could hope to answer, and to my delight, I have found many like minded people who have also asked the same questions. Not only that, they have even laid the foundation for me to do my own work. For this, I am eternally grateful. What an awesome opportunity today is.


#-------------------------------
# Faq (Frequently asked questions) Settings
faq:
  enable: true
  faq_title: Need Some Answers?
  faq_description:
  faq_items:
    - title: What drives you?
      description: I am driven by innovation and the opportunity to use technology in groundbreaking ways to achieve what was once thought impossible.
    - title: What are you currently interested in?
      description: I am deeply interested in Deep Reinforcement Learning (DRL) and its applications in continuous learning systems. I believe DRL will be a cornerstone of future technology, enabling transformative advancements like my financial agent bot.
    - title: What kinds of software projects do you work on?
      description: I focus on creating scalable and innovative solutions in data science, deep learning, and reinforcement learning. My projects often involve designing and implementing intelligent systems, from financial optimization models to real-time decision-making agents. I also work on custom tools and platforms to showcase the potential of advanced AI and machine learning in real-world applications.
    - title: Can you explain your experience with deep learning and reinforcement learning?
      description: I have hands-on experience developing and fine-tuning models for various deep learning applications, including natural language processing and time-series forecasting. In reinforcement learning, I specialize in creating agents capable of learning from environments to optimize performance, such as in financial portfolio optimization and dynamic decision-making scenarios. My work bridges theoretical research and practical implementation, delivering robust results.
    - title: What do you enjoy most about working in data science and machine learning?
      description: I enjoy the challenge of turning raw data into actionable insights and predictive models. Solving complex problems, uncovering patterns, and creating systems that learn and adapt are incredibly rewarding. I’m particularly inspired by the potential of machine learning to transform industries and improve decision-making processes in ways previously unimaginable.
    - title: What’s next for you in your career?
      description: I aim to deepen my expertise in reinforcement learning and explore its applications in fields like finance, robotics, and autonomous systems. My goal is to lead innovative projects that push the boundaries of AI and machine learning. I also plan to contribute to open-source initiatives and collaborate with like-minded professionals to shape the future of AI-driven solutions.

#-------------------------------
# Newsletter Settings
mailchimp:
  enable: false
  mailchimp_title: Stay inspired weekly. Your friendly dose of tips & insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Subscribe
  mailchimp_background_image: '/TimBunkerPortfolio/images/subscribe-bg.jpg'


#-------------------------------
# Social Links
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/TimothyBunker"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  contact_email: bunkertimothy0@gmail.com # Add your form_id
  contact_button_text: Send Message

# NOTE
# Renva theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
